#!/bin/bash

#create array of monitors (req  bash version > 4)
mapfile -t monitors < <(bspc query -M)
num_monitors=${#monitors[@]}
num_desktops=$((10 / $num_monitors))
a=1
b=$num_desktops
for i in "${!monitors[@]}"
do
    #monitor 
    monitor=${monitors[i]}

    #desktop count
    desktops=$(seq $a $b)

    #set desktops
    bspc monitor $monitor -n "$i" -d $desktops

    #update count for next monitor
    a=$(($a+$num_desktops))
    b=$(($b+$num_desktops))
done

bspc config border_width        2
bspc config window_gap         	5
bspc config top_padding  	15	

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true

bspc config normal_border_color "#181512"
bspc config active_border_color "#9a875f"
bspc config focused_border_color "#fafac0"
bspc config presel_border_color "#bec17e"
bspc config urgent_border_color "#756f7b"
bspc config focused_locked_border_color "#8c644c"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1


#RULES

bspc rule -a chromium monitor=1 



sxhkd &
panel &
chromium &
urxvt &

#open Funny Java Things
wmname LG3D
