#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-bar}

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &

. panel_colors

case "$flavor" in
	bar)
        #FONT1="-misc-stlarch-medium-r-normal-*-10-*-*-*-c-*-iso10646-1"
        FONT1="-*-dejavu sans mono-medium-r-normal--*-125-*-*-*-*-iso10646-1" 
        #FONT1="-misc-stlarch-medium-r-normal-*-10-100-75-75-c-80-iso10646-1"
        #FONT1="-misc-stlarch-medium-r-normal-*-17-*-*-*-*-*-iso10646-*"
		FONT2="-*-terminus-medium-r-normal-*-10-*-*-*-c-*-*-1"
		FONT_FAMILY="-*-terminus-medium-r-normal-*-10-*-*-*-c-*-*-1"
		cat "$PANEL_FIFO" | panel_bar | bar -g x$PANEL_HEIGHT \
                                            -f "$FONT1" \
                                            -F "$FOREGROUND" \
                                            -B "$BACKGROUND" &
		;;
	dzen2)
		FONT_FAMILY='DejaVu Sans'
		FONT_SIZE=11
		cat "$PANEL_FIFO" | panel_dzen2 -f "$FONT1,$FONT2" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &
		;;
esac

wait
